FROM apache/shardingsphere-proxy:5.5.1
RUN wget https://repo1.maven.org/maven2/io/vertx/vertx-grpc/4.5.1/vertx-grpc-4.5.1.jar --directory-prefix=/opt/shardingsphere-proxy/ext-lib
RUN wget https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.50.2/grpc-protobuf-1.50.2.jar --directory-prefix=/opt/shardingsphere-proxy/ext-lib
RUN wget https://repo1.maven.org/maven2/io/vertx/vertx-core/4.5.1/vertx-core-4.5.1.jar --directory-prefix=/opt/shardingsphere-proxy/ext-lib
